# Numpy

Материалы:
* Макрушин С.В. "Лекция 1: Библиотека Numpy"
* https://numpy.org/doc/stable/user/index.html
* https://numpy.org/doc/stable/reference/index.html

## Задачи для совместного разбора

1. Сгенерировать двухмерный массив `arr` размерности (4, 7), состоящий из случайных действительных чисел, равномерно распределенных в диапазоне от 0 до 20. Нормализовать значения массива с помощью преобразования вида  $𝑎𝑥+𝑏$  так, что после нормализации максимальный элемент масcива будет равен 1.0, минимальный 0.0

In [46]:
import numpy as np

m=np.random.randint(0, 21, size=(4,7))
norm_m = (m - np.min(m)) / (np.max(m) - np.min(m)) 
print(f'Массив:\n {m}; \nНормальзованный массив:\n {norm_m}')

Массив:
 [[ 5 18 17 14  8 13 14]
 [13 18  2 17  3  7 15]
 [14  8 14  3 14  3  6]
 [ 4 16  7  9 10 15 19]]; 
Нормальзованный массив:
 [[0.17647059 0.94117647 0.88235294 0.70588235 0.35294118 0.64705882
  0.70588235]
 [0.64705882 0.94117647 0.         0.88235294 0.05882353 0.29411765
  0.76470588]
 [0.70588235 0.35294118 0.70588235 0.05882353 0.70588235 0.05882353
  0.23529412]
 [0.11764706 0.82352941 0.29411765 0.41176471 0.47058824 0.76470588
  1.        ]]


2. Создать матрицу 8 на 10 из случайных целых (используя модуль `numpy.random`) чисел из диапозона от 0 до 10 и найти в ней строку (ее индекс и вывести саму строку), в которой сумма значений минимальна.

In [66]:
n=np.random.randint(0, 10, size=(8,10))
print(n)
lst=[]
for i in n:
    lst.append(np.sum(i))
print(f'Минимальная сумма значений - {min(lst)}. Индекс строки с минимальной суммой значений - {lst.index(min(lst))}')

[[4 3 4 7 3 3 3 3 9 9]
 [1 8 8 5 3 2 8 7 8 5]
 [4 8 7 4 1 8 2 4 8 8]
 [0 2 3 5 5 8 8 3 3 7]
 [4 2 0 9 5 7 5 3 4 2]
 [3 3 6 8 8 7 7 2 0 4]
 [3 3 5 4 3 2 1 6 0 5]
 [1 9 7 0 9 8 1 7 1 1]]
Минимальная сумма значений - 32. Индекс строки с минимальной суммой значений - 6


3. Найти евклидово расстояние между двумя одномерными векторами одинаковой размерности.

In [67]:
v1=np.random.randint(0, 10, size=3)
v2=np.random.randint(0, 10, size=3)
res=np.sqrt(np.sum(np.square(v1 - v2)))
print(f'Первый вектор:{v1}, второй вектор:{v2}. Евклидово расстояние:{res}')

Первый вектор:[5 2 8], второй вектор:[1 9 3]. Евклидово расстояние:9.486832980505138


4. Решить матричное уравнение `A*X*B=-C` - найти матрицу `X`. Где `A = [[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]]`, `B=[[3, -1], [2, 1]]`, `C=[[7, 21], [11, 8], [8, 4]]`.

In [82]:
a=np.array([[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]]).reshape(3,3)
b=np.array([[3, -1], [2, 1]]).reshape(2,2)
c=np.array([[7, 21], [11, 8], [8, 4]]).reshape(3,2)
x=np.dot(np.dot(np.linalg.inv(a), -c), np.linalg.inv(b))
x

array([[ 1.00000000e+00,  1.11022302e-15],
       [-2.00000000e+00,  1.00000000e+00],
       [ 3.00000000e+00, -4.00000000e+00]])

## Лабораторная работа №1

In [1]:
import numpy as np

Замечание: при решении данных задач не подразумевается использования циклов или генераторов Python, если в задании не сказано обратного. Решение должно опираться на использования функционала библиотеки `numpy`.

1. Файл `minutes_n_ingredients.csv` содержит информацию об идентификаторе рецепта, времени его выполнения в минутах и количестве необходимых ингредиентов. Считайте данные из этого файла в виде массива `numpy` типа `int32`, используя `np.loadtxt`. Выведите на экран первые 5 строк массива.

In [22]:
file=np.loadtxt("minutes_n_ingredients.csv", delimiter=',', dtype='int64', skiprows=1)
print(file[:5])

[[127244     60     16]
 [ 23891     25      7]
 [ 94746     10      6]
 [ 67660      5      6]
 [157911     60     14]]


In [29]:
file[:, 0]

array([127244,  23891,  94746, ..., 498432, 370915,  81993], dtype=int64)

In [30]:
16/60

0.26666666666666666

2. Вычислите среднее значение, минимум, максимум и медиану по каждому из столбцов, кроме первого.

In [23]:
sr=np.mean(file, axis=0)
print(f'Среднее по первому столбцу - {sr[1]}. Среднее по второму столбцу - {sr[2]}. ')
mx=np.max(file, axis=0)
print(f'Максимум по первому столбцу - {mx[1]}. Максимум по второму столбцу - {mx[2]}. ')
mn=np.min(file, axis=0)
print(f'Минимум по первому столбцу - {mn[1]}. Минимум по второму столбцу - {mn[2]}. ')
md=np.median(file, axis=0)
print(f'Медиана по первому столбцу - {md[1]}. Медиана по второму столбцу - {md[2]}. ')

Среднее по первому столбцу - 21601.00169. Среднее по второму столбцу - 9.05528. 
Максимум по первому столбцу - 2147483647. Максимум по второму столбцу - 39. 
Минимум по первому столбцу - 0. Минимум по второму столбцу - 1. 
Медиана по первому столбцу - 40.0. Медиана по второму столбцу - 9.0. 


3. Ограничьте сверху значения продолжительности выполнения рецепта значением квантиля $q_{0.75}$. 

In [15]:
qua=np.quantile(file, 0.75, axis=0)
print(qua[2])

11.0


4. Посчитайте, для скольких рецептов указана продолжительность, равная нулю. Замените для таких строк значение в данном столбце на 1.

In [19]:
n_zeros = np.count_nonzero(file==0, axis=0)
n_zeros

array([  0, 479,   0], dtype=int64)

5. Посчитайте, сколько уникальных рецептов находится в датасете.

In [10]:
un=np.unique(file[:, 0])
print(f'Уникальных рецептов - {len(un)}. ')

Уникальных рецептов - 100000. 


6. Сколько и каких различных значений кол-ва ингредиентов присутвует в рецептах из датасета?

In [13]:
unique, counts = np.unique(file[:, 2], return_counts=True)
result = np.column_stack((unique, counts)) 
print('Ингридиентов/Рецептов')
print (result)

Ингридиентов/Рецептов
[[    1    13]
 [    2   926]
 [    3  2895]
 [    4  5515]
 [    5  7913]
 [    6  9376]
 [    7 10628]
 [    8 10951]
 [    9 10585]
 [   10  9591]
 [   11  8297]
 [   12  6605]
 [   13  4997]
 [   14  3663]
 [   15  2595]
 [   16  1767]
 [   17  1246]
 [   18   790]
 [   19   573]
 [   20   376]
 [   21   217]
 [   22   161]
 [   23   105]
 [   24    69]
 [   25    50]
 [   26    28]
 [   27    16]
 [   28    16]
 [   29    12]
 [   30    12]
 [   31     3]
 [   32     1]
 [   33     2]
 [   34     1]
 [   35     3]
 [   37     1]
 [   39     1]]


7. Создайте версию массива, содержащую информацию только о рецептах, состоящих не более чем из 5 ингредиентов.

In [17]:
file1=file[file[:,2] <= 5]

file1

array([[446597,     15,      5],
       [204134,      5,      3],
       [ 25623,      6,      4],
       ...,
       [ 52088,     60,      5],
       [128811,     15,      4],
       [370915,      5,      4]], dtype=int64)

8. Для каждого рецепта посчитайте, сколько в среднем ингредиентов приходится на одну минуту рецепта. Найдите максимальное значение этой величины для всего датасета

In [34]:
avrg = np.divide(file[:, 2], file[:, 1], where=file[:, 1]!=0)
print(f'Максимальное значение - {np.max(avrg)}')
avrg

Максимальное значение - 23.0


array([0.26666667, 0.28      , 0.6       , ..., 0.23076923, 0.8       ,
       0.1       ])

9. Вычислите среднее количество ингредиентов для топ-100 рецептов с наибольшей продолжительностью

In [35]:
top100 = file[np.argsort(file[:, 1])][-100:, 2]
print(f' Cреднее количество ингредиентов для топ-100 рецептов с наибольшей продолжительностью - {np.average(top100)}')

 Cреднее количество ингредиентов для топ-100 рецептов с наибольшей продолжительностью - 6.61


10. Выберите случайным образом и выведите информацию о 10 различных рецептах

In [36]:
print(file[np.random.randint(file.shape[0], size = 10)])

[[192954    630     12]
 [ 87955     60     11]
 [171605    120     10]
 [103059      5      8]
 [290321     10      4]
 [380756     30      9]
 [301378      5      2]
 [ 25025     60      9]
 [ 39492     12      3]
 [ 66653     30     10]]


11. Выведите процент рецептов, кол-во ингредиентов в которых меньше среднего.

In [37]:
lessav=file[file[:,2] <= np.mean(file, axis=0)[2]]
print(f'Процент рецептов, кол-во ингредиентов в которых меньше среднего - {len(lessav)/len(file)*100}% ')

Процент рецептов, кол-во ингредиентов в которых меньше среднего - 58.802% 


12. Назовем "простым" такой рецепт, длительность выполнения которого не больше 20 минут и кол-во ингредиентов в котором не больше 5. Создайте версию датасета с дополнительным столбцом, значениями которого являются 1, если рецепт простой, и 0 в противном случае.

In [39]:
simplee=(file[:,1] <= 20) & (file[:,2] <= 5)
wsimp=np.hstack((file, simplee[:, np.newaxis]))
wsimp

array([[127244,     60,     16,      0],
       [ 23891,     25,      7,      0],
       [ 94746,     10,      6,      0],
       ...,
       [498432,     65,     15,      0],
       [370915,      5,      4,      1],
       [ 81993,    140,     14,      0]], dtype=int64)

13. Выведите процент "простых" рецептов в датасете

In [43]:
 print(f' Процент "простых" рецептов - {np.count_nonzero(wsimp[:, 3], axis=0)/len(file)*100} %')

 Процент "простых" рецептов - 9.552 %


14. Разделим рецепты на группы по следующему правилу. Назовем рецепты короткими, если их продолжительность составляет менее 10 минут; стандартными, если их продолжительность составляет более 10, но менее 20 минут; и длинными, если их продолжительность составляет не менее 20 минут. Создайте трехмерный массив, где нулевая ось отвечает за номер группы (короткий, стандартный или длинный рецепт), первая ось - за сам рецепт и вторая ось - за характеристики рецепта. Выберите максимальное количество рецептов из каждой группы таким образом, чтобы было возможно сформировать трехмерный массив. Выведите форму полученного массива.

In [45]:
short=file[file[:,1]<=10]
norm1=file[file[:,1]>10]
norm=norm1[norm1[:,1]<=20]
long=file[file[:,1]>20]

trehmer=np.arange(149592).reshape(3,12466,4)
trehmer[0][:,1:]=short[:12466,:]
trehmer[0][:,0]=0
trehmer[1][:,1:]=norm[:12466,:]
trehmer[1][:,0]=1
trehmer[2][:,1:]=long[:12466,:]
trehmer[2][:,0]=2
trehmer

array([[[     0,  94746,     10,      6],
        [     0,  67660,      5,      6],
        [     0, 366174,      7,      9],
        ...,
        [     0, 420725,      5,      3],
        [     0,   4747,      0,      9],
        [     0, 370915,      5,      4]],

       [[     1,  33941,     18,      9],
        [     1, 446597,     15,      5],
        [     1,  74205,     20,      7],
        ...,
        [     1, 230115,     20,      7],
        [     1, 496131,     20,      9],
        [     1, 365818,     20,      6]],

       [[     2, 127244,     60,     16],
        [     2,  23891,     25,      7],
        [     2, 157911,     60,     14],
        ...,
        [     2,  68428,     70,     10],
        [     2, 312995,   1445,      7],
        [     2,  93651,    240,     12]]])